Develop
Florian196/Systems-Development-and-Frameworks pull request #2
Opened 2019-11-13 13:25 UTC by Florian196

2019-11-13 14:12 UTC, menno4000 reviewed
Looks good to me. I did notice that you're not running your Linter in the continuous integration config. It's possible to add it to the script plan for the travis CI. 
Here is your obligatory gif reward
![Alt Text](https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif)

2019-11-13 19:08 UTC, Jeetee0 approved these changes
tests for list & listitem are there. maybe add tests for App.vue
travis build is also integrated

2019-11-13 19:08 UTC, Jeetee0 commented on src/components/List.spec.js
> +    });
all behaviour is tested :)

2019-11-17 22:06 UTC, roschaefer requested changes
![great](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)

Great! But could you please add a second check to your build server? I would like to see that you know how to configure the build server.

2019-11-17 22:06 UTC, roschaefer commented on .travis.yml
> +script:
Cool, `npm install` is automatically run by Travis CI.

2019-11-17 22:06 UTC, roschaefer commented on package.json
> -    "lint": "vue-cli-service lint"
Why you remove "lint" :cry: ?

2019-11-17 22:06 UTC, roschaefer commented on .travis.yml
> +  - npm test
But you should have one more check running here. My suggestion was to run the linter on the build server.

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.spec.js
> +const mountList = shallowMount(List, {
If you assign to a `const` whatever you do with `mountList` will be propgagated to other test cases. If you are only reading from `mountList` fine. But as far as I can see you are deleting sub-components from it. That will have an effect on the test cases that will follow. Thus, non-atomic tests and the execution order matters. That is bad and should be avoided.

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.spec.js
> +});
Therefore I'm proposing:

```js
const mountList = () => shallowMount(List, {
    headline: "ToDo-List",
    ToDoList: [
      {text: "Clean room"},
      {text: "Finish task1"},
      {text: "Add task2"}
    ],
    add_item_text: ""
});
```

And call it like this:

```js
const wrapper = mountList()
```

You could further customize the setup method in a way that would allow you to do:

```js
const wrapper = mountList({ propsData: { overwrite: "this" } })
```

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.spec.js
> +        expect(mountList.findAll(ListItem).length).toBe(3);
```suggestion
        expect(mountList.findAll(ListItem)).toHaveLength(3);
```

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.spec.js
> +        expect(mountList.findAll(ListItem).length).toBe(length + 1);
If you re-initialize your `mountList` either with a setup method :point_up: or with a `beforeEach` you could hard-code the expected length, which is much safer in my opinion.

https://jestjs.io/docs/en/setup-teardown

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.spec.js
> +    test('contains data', () => {
```suggestion
    test('renders `ListItem`s for each todo', () => {
```
Is probably more telling

2019-11-17 22:06 UTC, roschaefer commented on src/components/List.vue
> +                 v-on:deleteMyToDo="deleteMyToDo"
```suggestion
                 @deleteMyToDo="deleteMyToDo"
```

2019-11-17 22:06 UTC, roschaefer commented on src/components/ListItem.spec.js
> +    test('go in edit mode', () =>{
```suggestion
    test('click on edit button shows input field', () =>{
```
I like to put that into a `describe` block:
```js
describe('click on edit button', () => {
  beforeEach(() => mountItem.find("#edit").trigger("click"))

  it('shows input field', () => {
    expect(mountItem.contains("input")).toBe(true)
  })
})

2019-11-17 22:06 UTC, roschaefer commented on src/components/ListItem.spec.js
> +        expect(mountItem.props("item").text).toBe("edited");
This is so much easier to read than any of those checks of `wrapper.vm` which I saw in other assignments. You're testing the interface here. Well done :+1:

2019-11-17 22:06 UTC, roschaefer commented on src/components/ListItem.vue
> +  data: function() {
```suggestion
  data() {
```

2019-11-17 22:08 UTC, roschaefer commented
@Florian196 by the way, you didn't request a review from me, but assigned me to the PR. I fixed that:

![Screenshot - 2019-11-17T220013 384](https://user-images.githubusercontent.com/2110676/69014910-28efd100-098f-11ea-889b-15c8171bb5fa.png)

2019-11-20 12:30 UTC, merged